(defun half-blind ()
  (interactive)
  (color-theme-install
   '(half-blind
      ((background-color . "#f8f7f7")
      (background-mode . light)
      (border-color . "#ebebea")
      (cursor-color . "#000000")
      (foreground-color . "#000000")
      (mouse-color . "black"))
     (fringe ((t (:background "#ebebea"))))
     (mode-line ((t (:foreground "#ffffff" :background "#3b6865"))))
     (region ((t (:background "#b6b1f1"))))
     (font-lock-builtin-face ((t (:foreground "#170ce4"))))
     (font-lock-comment-face ((t (:italic t :foreground "#777"))))
     (font-lock-function-name-face ((t (:foreground "#0d27b5"))))
     (font-lock-keyword-face ((t (:foreground "#5c5c5c"))))
     (font-lock-string-face ((t (:italic t :foreground "#297f29"))))
     (font-lock-type-face ((t (:foreground"#0b7d07"))))
     (font-lock-variable-name-face ((t (:foreground "#4f4047"))))
     (erc-timestamp-face ((t (:foreground "Blue"))))
     (minibuffer-prompt ((t (:foreground "#020697" :background "yellow" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'half-blind)
